# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_run(object):
    def setupUi(self, run):
        run.setObjectName("run")
        run.setWindowModality(QtCore.Qt.NonModal)
        run.resize(409, 298)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        run.setFont(font)
        run.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        run.setStyleSheet("QDialog{\n"
"    background-color:#514E4F;\n"
"}\n"
"QPushButton{\n"
"    background-color:#A69FA2;\n"
"}\n"
"QGraphicsView{\n"
"    background-color:#514E4F;\n"
"}\n"
"QSlider{\n"
"    background-color:#514E4F;\n"
"}")
        run.setWindowFilePath("")
        run.setInputMethodHints(QtCore.Qt.ImhNone)
        run.setSizeGripEnabled(True)
        run.setModal(False)
        self.save = QtWidgets.QPushButton(run)
        self.save.setGeometry(QtCore.QRect(334, 262, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.km_runed = QtWidgets.QGraphicsView(run)
        self.km_runed.setGeometry(QtCore.QRect(10, 10, 391, 231))
        self.km_runed.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.km_runed.setAcceptDrops(True)
        self.km_runed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.km_runed.setObjectName("km_runed")
        self.save_2 = QtWidgets.QPushButton(run)
        self.save_2.setGeometry(QtCore.QRect(10, 260, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.save_2.setFont(font)
        self.save_2.setObjectName("save_2")
        self.save_3 = QtWidgets.QPushButton(run)
        self.save_3.setGeometry(QtCore.QRect(80, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.save_3.setFont(font)
        self.save_3.setObjectName("save_3")

        self.retranslateUi(run)
        QtCore.QMetaObject.connectSlotsByName(run)

    def retranslateUi(self, run):
        _translate = QtCore.QCoreApplication.translate
        run.setWindowTitle(_translate("run", "Dialog"))
        self.save.setText(_translate("run", "save"))
        self.save_2.setText(_translate("run", "add"))
        self.save_3.setText(_translate("run", "add user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    run = QtWidgets.QDialog()
    ui = Ui_run()
    ui.setupUi(run)
    run.show()
    sys.exit(app.exec_())
